"""user sessions

Revision ID: ed32da0e379f
Revises: ed7ee80f163c
Create Date: 2025-11-14 18:58:59.981646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed32da0e379f"
down_revision: Union[str, None] = "ed7ee80f163c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_sessions",
        sa.Column("user_uuid", sa.String(length=36), nullable=False),
        sa.Column("token_jti", sa.String(length=36), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("browser", sa.String(length=50), nullable=True),
        sa.Column("browser_version", sa.String(length=20), nullable=True),
        sa.Column("os", sa.String(length=50), nullable=True),
        sa.Column("os_version", sa.String(length=20), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=True),
        sa.Column("location_city", sa.String(length=100), nullable=True),
        sa.Column("location_region", sa.String(length=100), nullable=True),
        sa.Column("location_country", sa.String(length=10), nullable=True),
        sa.Column("location_country_name", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("views", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("delete_protection", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_user_sessions_created_at"),
        "user_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_is_active"), "user_sessions", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_user_sessions_last_active"),
        "user_sessions",
        ["last_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_token_jti"), "user_sessions", ["token_jti"], unique=True
    )
    op.create_index(
        op.f("ix_user_sessions_updated_at"),
        "user_sessions",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_sessions_user_uuid"), "user_sessions", ["user_uuid"], unique=False
    )
    op.add_column(
        "users", sa.Column("last_login", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_login")
    op.drop_index(op.f("ix_user_sessions_user_uuid"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_updated_at"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_token_jti"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_last_active"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_is_active"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_created_at"), table_name="user_sessions")
    op.drop_table("user_sessions")
    # ### end Alembic commands ###
